### PR TITLE
Update Dockerfile for upgraded composer and xdebug

### PR DESCRIPTION
**Pull request by otis22**

### CODE REVIEW

**Comment by otis22** [comment]
I will fix it after similar fix in arrayee

**Comment by stepanets** [comment]
@otis22 lets reopen it instead creating a new one

**Comment by otis22** [comment]
I've fixed

**Review by stepanets — APPROVED** [review]

**Comment by otis22** [comment]
@stepanets need I  to do something else with this request?

**Comment by tigokr** [comment]
@otis22 thanks, good work

**Pull request merged**
